#!/bin/bash
MIN_VERSION="7.4.0"
PHP_VERSION=$(php -r 'echo PHP_VERSION;')

function version_compare() {
  COMPARE_OP=$1
  TEST_VERSION=$2
  RESULT=$(php -r 'echo version_compare(PHP_VERSION, "'"${TEST_VERSION}"'", "'"${COMPARE_OP}"'") ? "TRUE" : "";')

  test -n "${RESULT}"
}

echo "PHP VERSION: ${PHP_VERSION}"
if (version_compare ">" "${MIN_VERSION}"); then
  pecl install sqlsrv
  pecl install pdo_sqlsrv
else
  pecl install sqlsrv-5.6.1
  pecl install pdo_sqlsrv-5.6.1
fi
pecl clear-cache
docker-php-ext-enable pdo_sqlsrv
